### ISSUE TITLE
Bug / Typo - Compound Bow

### ISSUE THREAD

**Issue by Ynd21** [jordsti/ark-itemizer#10]
Heya, 

Just downloaded the new items (I added these on my own item list a lil bit ago, but have no idea how to push my updates to github to help out), it looks like theres a typo in your item list - Compund Bow should be Compound Bow :) Thanks!

**Comment by jordsti** [comment]
You need to make a pull request, then I can accept it and merge it with my code base.

But it's gonna for the next time.

It's fixed now
